---
deployment:
  tasks:
    - export DEPLOYPATH=/home/architex/public_html/axis
    
    # Copy files
    - /bin/cp -R * $DEPLOYPATH
    
    # Copy dot files
    - /bin/cp .env.production $DEPLOYPATH/.env
    - /bin/cp .htaccess $DEPLOYPATH/
    
    # Set permissions
    - /bin/chmod 755 $DEPLOYPATH/storage -R
    - /bin/chmod 755 $DEPLOYPATH/bootstrap/cache -R
    
    # Laravel commands
    - cd $DEPLOYPATH && php artisan key:generate --force
    - cd $DEPLOYPATH && php artisan storage:link
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
    - cd $DEPLOYPATH && php artisan optimize
