<x-layouts.admin>
    <x-slot name="header">
        {{ __('Reports') }}
    </x-slot>

    <div class="py-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <!-- Report Categories -->
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
                <!-- Job Progress Report Card -->
                <a href="{{ route('admin.reports.job-progress') }}" class="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
                    <div class="flex items-center space-x-4">
                        <div class="p-3 bg-blue-500 bg-opacity-20 rounded-full">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                            </svg>
                        </div>
                        <div>
                            <h3 class="text-lg font-semibold text-gray-800">Job Progress Reports</h3>
                            <p class="text-sm text-gray-500">View detailed status and progress of all jobs</p>
                        </div>
                    </div>
                </a>

                <!-- Freelancer Performance Report Card -->
                <a href="{{ route('admin.reports.freelancer-performance') }}" class="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
                    <div class="flex items-center space-x-4">
                        <div class="p-3 bg-green-500 bg-opacity-20 rounded-full">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </div>
                        <div>
                            <h3 class="text-lg font-semibold text-gray-800">Freelancer Performance</h3>
                            <p class="text-sm text-gray-500">Analyze productivity and quality metrics for freelancers</p>
                        </div>
                    </div>
                </a>

                <!-- Client Project Status Report Card -->
                <a href="{{ route('admin.reports.client-project-status') }}" class="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
                    <div class="flex items-center space-x-4">
                        <div class="p-3 bg-purple-500 bg-opacity-20 rounded-full">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-purple-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                            </svg>
                        </div>
                        <div>
                            <h3 class="text-lg font-semibold text-gray-800">Client Project Status</h3>
                            <p class="text-sm text-gray-500">Overview of project statuses for each client</p>
                        </div>
                    </div>
                </a>
            </div>

            <!-- Recent Activity -->
            <div class="bg-white p-6 rounded-xl shadow-lg">
                <h3 class="text-lg font-semibold text-gray-800 mb-4">Recent Report Activity</h3>
                
                <div class="overflow-x-auto">
                    <table class="min-w-full bg-white">
                        <thead class="bg-gray-100">
                            <tr>
                                <th class="py-3 px-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Report Type</th>
                                <th class="py-3 px-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated By</th>
                                <th class="py-3 px-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                                <th class="py-3 px-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-200">
                            <!-- Sample data - in a real app, this would be populated from the database -->
                            <tr>
                                <td class="py-3 px-4 whitespace-nowrap">Job Progress Report</td>
                                <td class="py-3 px-4 whitespace-nowrap">Admin</td>
                                <td class="py-3 px-4 whitespace-nowrap">{{ now()->subDays(1)->format('M d, Y') }}</td>
                                <td class="py-3 px-4 whitespace-nowrap">
                                    <a href="{{ route('admin.reports.job-progress') }}" class="text-blue-600 hover:text-blue-900">View</a>
                                </td>
                            </tr>
                            <tr>
                                <td class="py-3 px-4 whitespace-nowrap">Freelancer Performance</td>
                                <td class="py-3 px-4 whitespace-nowrap">Admin</td>
                                <td class="py-3 px-4 whitespace-nowrap">{{ now()->subDays(3)->format('M d, Y') }}</td>
                                <td class="py-3 px-4 whitespace-nowrap">
                                    <a href="{{ route('admin.reports.freelancer-performance') }}" class="text-blue-600 hover:text-blue-900">View</a>
                                </td>
                            </tr>
                            <tr>
                                <td class="py-3 px-4 whitespace-nowrap">Client Project Status</td>
                                <td class="py-3 px-4 whitespace-nowrap">Admin</td>
                                <td class="py-3 px-4 whitespace-nowrap">{{ now()->subDays(5)->format('M d, Y') }}</td>
                                <td class="py-3 px-4 whitespace-nowrap">
                                    <a href="{{ route('admin.reports.client-project-status') }}" class="text-blue-600 hover:text-blue-900">View</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-layouts.admin>
